version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=VideoStreaming
    ports:
      - 3307:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
